#!/usr/bin/env node
// KEEP THE BROWSER SIDECAR RUNNING, across a logout and a reboot.
//
// Usage:
//   node deploy/browser/install.mjs            install and start it
//   node deploy/browser/install.mjs --print    show the unit file and change nothing
//   node deploy/browser/install.mjs --remove   stop it and take it away
//
// Optional, and deliberately so: `npm run browser` in a terminal is the whole feature. This
// exists for the person who does not want to remember that after every reboot.
//
// IT IS A USER SERVICE, NEVER A SYSTEM ONE, and that is not a preference. The sidecar launches
// a real browser, and that browser must run as YOU, in YOUR graphical session, with YOUR
// keyring, or it has no window server to draw into and nothing to decrypt a profile with. A
// root service would either fail to start a browser at all or start one that could not see any
// of your logins. So: launchd LaunchAgent on macOS, systemd --user unit on Linux, no sudo
// either way.
//
// The paths are computed HERE, at install time, from where this repo actually is, and written
// into the generated file. That is why this is a script and not a checked-in plist: a service
// definition needs absolute paths, and absolute paths are exactly what must never be committed
// to this repo.
import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url))));
const LABEL = "attention-hub-browser";
const mode = process.argv.includes("--remove") ? "remove" : process.argv.includes("--print") ? "print" : "install";

function die(message) {
  console.error(`[install] ${message}`);
  process.exit(1);
}

/** The node that is running this is the node the service should run, absolute, because a
 * service manager's PATH does not include a version manager's shims. */
const nodeBin = process.execPath;

function sidecarPort() {
  for (const file of ["hub.config.json", "hub.config.example.json"]) {
    const full = path.join(appRoot, file);
    if (!existsSync(full)) continue;
    try {
      const raw = JSON.parse(readFileSync(full, "utf8"));
      const port = raw?.browser?.sidecarPort;
      if (Number.isInteger(port)) return port;
    } catch {
      // fall through
    }
  }
  return null;
}

// The sidecar's own dependency has to be installed, or the service starts, fails, and gets
// restarted forever by a manager that cannot tell you why.
if (!existsSync(path.join(appRoot, "chrome", "node_modules", "ws"))) {
  die("the sidecar's dependency is missing. Run: npm run browser:install");
}

const port = sidecarPort();
console.log(`[install] hub at ${appRoot}`);
console.log(`[install] node   ${nodeBin}`);
console.log(`[install] port   ${port ?? "unknown (no browser.sidecarPort in config)"}`);
console.log("");

// ------------------------------------------------------------------ macOS

const plist = () => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- The Attention Hub browser sidecar. A LaunchAGENT, not a daemon: it launches a real
     browser, which must run as this user in this graphical session or it has no window
     server to draw into and no keychain to unlock a profile with. Generated by
     deploy/browser/install.mjs; edit that, not this. The server binds loopback itself. -->
<plist version="1.0"><dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key><array>
    <string>${nodeBin}</string>
    <string>server.mjs</string>
  </array>
  <key>WorkingDirectory</key><string>${path.join(appRoot, "chrome")}</string>
  <key>EnvironmentVariables</key><dict>
    <key>PATH</key><string>${path.dirname(nodeBin)}:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${path.join(os.homedir(), "Library", "Logs", `${LABEL}.log`)}</string>
  <key>StandardErrorPath</key><string>${path.join(os.homedir(), "Library", "Logs", `${LABEL}.log`)}</string>
</dict></plist>
`;

const plistPath = path.join(os.homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);

function macos() {
  const domain = `gui/${process.getuid?.() ?? ""}`;
  if (mode === "print") {
    console.log(plist());
    console.log(`[install] would be written to ${plistPath}`);
    return;
  }
  // bootout first, always. A hand-started sidecar still holding the port makes the managed
  // copy die on EADDRINUSE, and KeepAlive then respawns it into the same wall forever.
  spawnSync("launchctl", ["bootout", `${domain}/${LABEL}`], { stdio: "ignore" });
  if (mode === "remove") {
    if (existsSync(plistPath)) unlinkSync(plistPath);
    console.log("[install] removed. Killing the sidecar never touches a browser: they are");
    console.log("[install] detached and outlive it by design.");
    return;
  }
  mkdirSync(path.dirname(plistPath), { recursive: true });
  writeFileSync(plistPath, plist());
  const out = spawnSync("launchctl", ["bootstrap", domain, plistPath], { encoding: "utf8" });
  if (out.status !== 0) die(`launchctl bootstrap failed: ${out.stderr || out.stdout}`);
  console.log(`[install] loaded ${LABEL}. Log: ~/Library/Logs/${LABEL}.log`);
}

// ------------------------------------------------------------------ Linux

const unit = () => `[Unit]
Description=Attention Hub browser sidecar
Documentation=file://${path.join(appRoot, "docs", "browser-pane.md")}
After=graphical-session.target

[Service]
Type=simple
WorkingDirectory=${path.join(appRoot, "chrome")}
ExecStart=${nodeBin} server.mjs
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
`;

const unitPath = path.join(
  process.env["XDG_CONFIG_HOME"] ?? path.join(os.homedir(), ".config"),
  "systemd",
  "user",
  `${LABEL}.service`,
);

function linux() {
  if (mode === "print") {
    console.log(unit());
    console.log(`[install] would be written to ${unitPath}`);
    return;
  }
  if (mode === "remove") {
    spawnSync("systemctl", ["--user", "disable", "--now", `${LABEL}.service`], { stdio: "ignore" });
    if (existsSync(unitPath)) unlinkSync(unitPath);
    spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "ignore" });
    console.log("[install] removed. Killing the sidecar never touches a browser: they are");
    console.log("[install] detached and outlive it by design.");
    return;
  }
  mkdirSync(path.dirname(unitPath), { recursive: true });
  writeFileSync(unitPath, unit());
  spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "inherit" });
  const out = spawnSync("systemctl", ["--user", "enable", "--now", `${LABEL}.service`], { encoding: "utf8" });
  if (out.status !== 0) die(`systemctl failed: ${out.stderr || out.stdout}`);
  console.log(`[install] enabled ${LABEL}.service. Log: journalctl --user -u ${LABEL} -f`);
  // A user service normally stops at logout, which is the wrong shape for something that is
  // supposed to be there after a reboot. Say so rather than silently needing it.
  console.log("[install] note: a user service stops when you log out. To keep it across a");
  console.log(`[install] reboot without logging in: sudo loginctl enable-linger ${os.userInfo().username}`);
}

// ------------------------------------------------------------------

if (process.platform === "darwin") macos();
else if (process.platform === "linux") linux();
else die(`the browser pane runs on macOS and Linux, and this machine is ${process.platform}.`);

if (mode === "install") {
  console.log("");
  console.log("[install] next, ONCE per profile, with that browser fully quit:");
  console.log("[install]   node scripts/seed-browser-profile.mjs");
  console.log("[install] then open a browser pane and pick the profile.");
}
